export const SAVE_USER_NAME = "SAVE_USER_NAME";
export const CHANGE_COLUMN_NAME = "CHANGE_COLUMN_NAME";
export const CREATE_NEW_CARD = "CREATE_NEW_CARD";
export const EDIT_CARD = "EDIT_CARD";
export const DELETE_CARD = "DELETE_CARD";

export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";

